<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<p>
    <a class="btn btn-primary" href="<?= $this->url('Members:Admin:Members@addAction'); ?>"><?= $this->translate('Add new member'); ?></a>
</p>

<div class="card">
    <?php $this->loadPartial('items-per-page', array('caption' => 'Members')); ?>
    <div class="table-responsive">
        <?= $this->widget(new GridViewWidget($members, array(
            'tableClass' => 'table table-hover table-bordered table-striped',
            'rowAttributes' => array(
                'class' => function($member){
                    return $member->getConfirmed() ? null : 'table-warning';
                }
            ),

            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name'
                ),

                array(
                    'column' => 'email'
                ),

                array(
                    'column' => 'login'
                ),

                array(
                    'column' => 'phone'
                ),

                array(
                    'column' => 'address'
                ),

                array(
                    'column' => 'subscriber',
                    'translateable' => true,
                    'value' => function($member){
                        return $member->getSubscriber() ? 'Yes' : 'No';
                    }
                )
            ),

            'actions' => array(
                function($member){
                    return Icon::edit(
                        $this->url('Members:Admin:Members@editAction', $member->getId()),
                        $this->translate('Edit this member')
                    );
                },

                function($member){
                    return Icon::remove(
                        $this->url('Members:Admin:Members@deleteAction', $member->getId()),
                        $this->translate('Remove this member')
                    );
                }
            )

        ))); ?>

        <?php if (empty($members)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No members'); ?></h2>
        </div>
        <?php endif; ?>
    </div>

    <?php $this->loadPartial('paginator'); ?>
</div>
