<?php

use Krystal\Form\Element;
use Krystal\Widget\GridWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<?php $this->loadPartial('items-per-page', array('caption' => 'Members')); ?>

<form>
    <div class="table-responsive">
        <?= $this->widget(new GridWidget($members, array(
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'rowAttributes' => array(
                'class' => function($member){
                    return $member->getConfirmed() ? null : 'warning';
                }
            ),

            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name'
                ),

                array(
                    'column' => 'email'
                ),

                array(
                    'column' => 'login'
                ),

                array(
                    'column' => 'phone'
                ),

                array(
                    'column' => 'address'
                ),

                array(
                    'column' => 'subscriber',
                    'translateable' => true,
                    'value' => function($member){
                        return $member->getSubscriber() ? 'Yes' : 'No';
                    }
                )
            ),

            'actions' => array(
                'remove' => function($member){
                    return Icon::remove(
                        $this->url('Members:Admin:Members@deleteAction', $member->getId()),
                        $this->translate('Remove this member')
                    );
                }
            )

        ))); ?>

		<?php if (empty($members)): ?>
		<div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No members'); ?></h2>
		</div>
		<?php endif; ?>
	</div>
</form>

<?php $this->loadPartial('paginator'); ?>
