<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<?php $this->loadPartial('items-per-page', array('caption' => 'Members')); ?>

<form>
    <div class="table-responsive">
        <table class="table table-hover table-bordered table-striped">
            <thead>
                <tr>
                    <th class="text-center">
                        <?php if (!empty($members)): ?>
                        <input type="checkbox" />
                        <?php endif; ?>
					</th>
					<th class="text-center"><?php $this->show('#'); ?></th>
					<th class="text-center"><?php $this->show('Name'); ?></th>
					<th class="text-center"><?php $this->show('Email'); ?></th>
					<th class="text-center"><?php $this->show('Login'); ?></th>
					<th class="text-center"><?php $this->show('Phone'); ?></th>
					<th class="text-center"><?php $this->show('Address'); ?></th>
					<th class="text-center"><?php $this->show('Subscriber'); ?></th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
			</thead>

            <?php if (!empty($members)): ?>
			<tbody>
				<?php foreach ($members as $member): ?>
				<tr class="<?php echo $member->getConfirmed() ? null : 'warning'; ?>">
                    <td class="text-center">
						<input type="checkbox" name="toDelete[<?php echo $member->getId(); ?>]" />
					</td>
					<td class="text-center text-muted"><?php echo $member->getId(); ?></td>
					<td class="text-center"><?php echo $member->getName(); ?></td>
					<td class="text-center"><?php echo $member->getEmail(); ?></td>
					<td class="text-center"><?php echo $member->getLogin(); ?></td>
					<td class="text-center"><?php echo $member->getPhone(); ?></td>
					<td class="text-center"><?php echo $member->getAddress(); ?></td>
					<td class="text-center"><?php $this->show($member->getSubscriber() ? 'Yes' : 'No'); ?></td>
					<td class="text-center">
                        <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this member'); ?>" data-button="delete" href="#" data-url="<?php echo $this->url('Members:Admin:Members@deleteAction', $member->getId()); ?>"><i class="glyphicon glyphicon-remove"></i></a>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
			<?php endif; ?>
		</table>
		
		<?php if (empty($members)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No members'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</form>

<?php $this->loadPartial('paginator'); ?>
